### ISSUE TITLE
uwsgi issues

### ISSUE THREAD

**Issue by dducted** [etesync/server#26] opened 2019-10-21 20:05 UTC
I have been trying to setup `uwsgi` however I run into a few issues.

I have set my `etesync.ini` as follows:
```
[uwsgi]
socket = /tmp/etesync.sock
chown-socket = ubuntu:www-data
chmod-socket = 660
vacuum = true

uid = ubuntu
chdir = /mnt/HDD/server-skeleton
home = %(chdir)/.venv
module = etesync_server.wsgi
master = true
```

The error I am getting right now in the log file when I restart uwsgi (`sudo service uwsgi restart`) is:
`Fatal Python error: Py_Initialize: Unable to get the locale encoding`
`ImportError: No module named 'encodings'`
_(I did google the error however I was not able to solve the issue)_

I am also not sure, once I get the uwsgi working how do I start it?
In my etesync venv home folder with:
`uwsgi --http :8000 --module etesync_server.wsgi`?

Thanks for your help, it is much appreciated.

**Comment by tasn** [comment] 2019-10-22 06:56
If you want it to serve using http and port 8000, you don't need to enable sockt.
```
[uwsgi]
vassal_name = etesync_server

disable-logging = True
chdir           = /mnt/HDD/server-skeleton
master          = true
module          = %(vassal_name).wsgi
home            = %(chdir)/.venv
uid = ubuntu

http-socket = :8000

env = PYTHONHASHSEED=random
env = DJANGO_SETTINGS_MODULE=%(vassal_name).settings.production
plugins = python

vacuum = true
```

Try this and let me know if it works.

**Comment by dducted** [comment] 2019-10-22 16:57
Awesome, thank for the response. I did the changes but I am left with a permission error, but I believe Ive set them all correctly...

```
Tue Oct 22 16:56:25 2019 - chdir() to /mnt/HDD/server-skeleton
Tue Oct 22 16:56:25 2019 - chdir(): Permission denied [core/uwsgi.c line 2586]
```

**Comment by tasn** [comment] 2019-10-22 17:13
I think linux disagrees. :)

Best way to test:
```
sudo -u ubuntu -i
cd /mnt/HDD/server-skeleton
```

**Comment by dducted** [comment] 2019-10-22 18:33
Yes for sure, linux does not agree with me - as usual :D

I did run the commands and I had no issues to access the folder.
https://i.imgur.com/t1C4Zmi.jpg

**Comment by tasn** [comment] 2019-10-22 19:38
Under what user are you running the uwsgi daemon? Root I hope?

I have no clue unfortunately, maybe talk to the uwsgi people for help?

**Comment by dducted** [comment] 2019-10-23 00:50
I re-installed my ubuntu, but this time I got a different error...

```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'
```

A little frustrating. Do I really need to run it under ugswi/nginx?

Thanks again for your help!

**Comment by tasn** [comment] 2019-10-23 05:46
Maybe try installing the package that provides encoding?
Just to make something clear `home = %(chdir)/.venv` means that everything is installed in a virtual env. If you haven't used a virtualenv, you should remove this line. This could very well be the cause of your issues.

As for your question: that's what the django people recommend. It's not coming from us. I guess it could be fine to run just with runserver, though they don't recommend it, so I wouldn't too.

**Comment by dducted** [comment] 2019-10-23 15:33
I also ran it in an venv. I might just ditch it. I also just run it locally, maybe that makes it a little better.

**Comment by tasn** [comment] 2019-10-23 17:15
I run it with uwsgi and a venv too.

Have you installed all of the required dependencies? P.S, I just realised, are you using python3? That actually may be the issue, I think ubuntu defaults to python2 so you have to tell uwsgi to specifically use python3. Google it, I'm not sure about the details.

**Comment by dducted** [comment] 2019-10-23 20:31
I do have all dependencies however I'm not sure its running off py2 or py3. I'll look into that. Thank you. 

Could you tell me, what's the command to run it once I got it, hopefully, working?

**Comment by eomanis** [comment] 2019-10-23 22:25
> I do have all dependencies however I'm not sure its running off py2 or py3.

EteSync uses Python 3 (at least on Arch Linux).

> I re-installed my ubuntu, but this time I got a different error...
> 
> ```
> Fatal Python error: Py_Initialize: Unable to get the locale encoding
> ModuleNotFoundError: No module named 'encodings'
> ```

This is an error that I encountered as well, and I was not able to solve it either. After too many failed attempts I decided to cut my losses and use a workaround instead.

The workaround I am using is calling `uwsgi` with everything it needs given as command line arguments instead of using an `.ini` file.

It can be seen in the `ExecStart=` entry in the `systemd` service unit that I wrote for running EteSync, `/etc/systemd/system/uwsgi-etesync.service`:
```
[Unit]
Description=uWSGI running etesync

[Service]
PrivateDevices=yes
PrivateTmp=yes
User=etesync
WorkingDirectory=/usr/lib/etesync-server
ExecStart=/usr/bin/uwsgi \
	--plugin=/usr/lib/uwsgi/python_plugin.so \
	--socket=/path/to/etesync/socket/etesync_server.sock \
	--chmod-socket=660 \
	--vacuum \
	--module=etesync_server.wsgi
SuccessExitStatus=15 17 29 30

[Install]
WantedBy=multi-user.target
```

**Comment by tasn** [comment] 2019-10-24 06:22
Hey @eomanis, thanks for pitching in!

Arch uses Python3 by default, I wonder if `plugin=/usr/lib/uwsgi/python_plugin.so` would be the same for Ubuntu.

Have you fellas tried running `pip install -r encodings` inside the venv?
@dducted: it works for you inside the venv manually, right?

Could you try for a second with removing the `uid=ubuntu` line?

**Comment by dducted** [comment] 2019-10-24 15:32
Thank you very much for the input @eomanis for the input. I'll give it a try and report back. 

@tasn, yes my etesync works just fine in the venv. I'll install encodings as well as removing the `uid` line.

**Comment by eomanis** [comment] 2019-10-24 21:05
> Have you fellas tried running `pip install -r encodings` inside the venv?

I'm not using a venv, but anyhow, it appears that the `encodings` module is shipped with Arch Linux's `python` package:
```
[root@mysystem ~]# find /usr/lib -path "*/encodings/__init__.py"
/usr/lib/python3.7/encodings/__init__.py
[root@mysystem ~]# pacman -Qo /usr/lib/python3.7/encodings/__init__.py 
/usr/lib/python3.7/encodings/__init__.py is owned by python 3.7.4-2
```
Now, I could go on a wild goose chase in yet-unfamiliar-to-me Python/uWSGI territory as to why `uwsgi` can't seem to find it (and likely learn something while doing so), or I can slack off and keep using the arguments-only solution where I incidentally have one configuration file less to maintain ;-)

Right now I can't quite find the energy to properly sort out this thing. If I ever do solve it I'll keep you posted, unless I forget.

**Comment by tasn** [comment] 2019-10-25 09:00
He's running uwsgi in a virtualenv, so it'd have to be present in the venv. I wonder why it's not pulled (or copied to the venv for that matter). I still think it may be an issue with ubuntu defaulting to python 2, or at least the env was built with python2. Though that wouldn't explain why it worked just fine with uwsgi.

@dducted, from inside the venv, what does python --version show?

**Comment by maxmopp** [comment] 2019-12-07 19:15
I had the same issues on Ubuntu 1804. Used virtualenv and pip3 and added the plugins=python3 line to ini. What made it work for me was changing the home path to the correct location:

`home = %(chdir)/../venv`

works as expected

**Comment by tasn** [comment] 2019-12-09 15:56
@maxmopp, thanks for sharing the info. Is the home path not the correct one when you follow the install instructions, or was it just that you accidentally created the venv in the wrong place? Because
`%(chdir)/.venv` is correct and the venv should indeed be in `.venv` and not `../venv`.

**Comment by daftaupe** [comment] 2020-01-21 22:32
I see that this ticket is not closed yet so I'm adding a note about another Python WSGI HTTP Server, called gunicorn, which is officially supported by Django as mentionned here https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/gunicorn/. I think it's a bit easier to configure it than uwsgi (as it's a much simpler piece of software), so it might help @dducted.

Here's a little notice on how to set it up : 
```
# change to the dir where you cloned the repo (I've tried to used your path, but I could be wrong)
cd /mnt/HDD/server-skeleton
# enter the virtual env
. .venv/bin/activate
# install gunicorn
pip install gunicorn
# start gunicorn
gunicorn etesync_server.wsgi:application
# you can specify the ip you want to bind to with gunicorn -b 192.168.1.10 etesync_server.wsgi:application for example
```

That will start a process listening on 127.0.0.1:8000 to which you can plug a reverse-proxy for example.

Regards,

**Comment by tasn** [comment] 2020-01-22 07:14
Looks simpler indeed, thanks for sharing!

As for this ticket. I'm going to close it now. From the above it looks like things are fine and it's just a matter of putting the virtualenv in the wrong path. If I'm mistaken and it's not the case, let me know and I'll open it again.

**Closed by tasn** 2020-01-22 07:14 UTC
