### ISSUE TITLE
Support for iCalendar tokens

### ISSUE THREAD

**Issue by lonkaars** [etesync/server#47] opened 2020-06-16 09:05 UTC
Is it possible to implement syncing with iCalendar servers? My school hosts their timetable using iCalendar and I'd like to view the events inside the etesync web client.

**Comment by tasn** [comment] 2020-06-16 09:38
Hey,

I'm closing this as it's a duplicate of https://github.com/etesync/etesync-web/issues/58
Please watch that one for updates.

Thanks!

**Closed by tasn** 2020-06-16 09:38 UTC
