### ISSUE TITLE
Can't connect with etesync-dav

### ISSUE THREAD

**Issue by zv0n** [etesync/server#79] opened 2020-12-07 15:23 UTC
Hi, I'm trying to host my own instance of etebase, all seems to be working except etesync-dav connection.

I'm running etebase with daphne and I'm accessing it via apache proxy, when I try to connect via android app there is no problem, but when I try connecting via etesync-dav, I get: HTTP error 400! Code: 'wrong_host'. Detail: 'Found wrong host name. Got: "$hostname" expected: "127.0.0.1:8001"'

Is there anything in the server settings I can change to fix this or is this a DAV issue?

**Comment by tasn** [comment] 2020-12-07 15:31
Duplicate of #66 
Essentially the problem is that you misconfigured your Apache. You need to forward the the Host header to the Etebase server.
See [the production section](https://github.com/etesync/server#production-deployment) of the README for more information.

**Closed by tasn** 2020-12-07 15:31 UTC
Labels: duplicate
